import Head from 'next/head';
import Image from 'next/image';
import homeStyles from '../styles/Home.module.css';
import React, { useState } from 'react';
import List from '../components/list';

interface IState {
  people: {
    name: string;
    age: number;
    url?: string;
    quote?: string;
  }[];
}

export default function Home() {
  const [people, setPeople] = useState<IState['people']>([
    {
      name: 'James Franco',
      url: 'https://3.bp.blogspot.com/-jarLeLW69Fk/Us3wGo3eIYI/AAAAAAAAQ4o/uY9HzM6H1W8/s1600/reg_1024.ThisistheEnd.JamesFranco.122012.jpg',
      age: 35,
      quote: ' Cool it, Dumbledore!',
    },
    {
      name: 'Danny McBride',
      url: 'https://cdn3.whatculture.com/images/2020/07/07ac2202ae8bf856-600x338.jpg',
      age: 36,
      quote:
        "You're making me into a joke right now Franco, and you are not gonna like the fucking punchline.",
    },
  ]);

  return (
    <div className='w-screen h-screen flex justify-center items-center'>
      <Head>
        <title>Party Planner</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='text-center p-24 min-h-screen min-w-full'>
        <h1 className='text-8xl font-bold'>
          <a href='https://nextjs.org' className='text-purple-500'>
            Party
          </a>{' '}
          Planner
        </h1>
        <List people={people} />
        {/* <ul className='my-10 space-y-5'>
          <li className='text-3xl'>
            Update homepage at{' '}
            <code className={homeStyles.code}>pages/index.js</code>
          </li>
          <li className='text-3xl'>
            Add pages to <code className={homeStyles.code}>pages/...</code>
          </li>
          <li className='text-3xl'>
            Add redux slices to{' '}
            <code className={homeStyles.code}>features/...</code>
          </li>
        </ul> */}
        {/* <p className='my-10'>
        </p> */}
      </main>
    </div>
  );
}
